version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:18.19.0
  working_directory: ~/app

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - "package.json"
            - "package-lock.json"
            - ".firebaserc"
            - "firebase.json"
            - "node_modules"
            - ".git/*"
            - ".circleci/*"
            - "src/*"

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Deploy
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2

  branch-workflow:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only:
                - main
